"""Base HTML email template module.

This module provides the core HTML template structure and common styling
used across all email types.
"""

from datetime import datetime


class BaseEmailTemplate:
    """Base class for HTML email templates with responsive design."""

    # Logo configuration - update this URL to your hosted logo
    LOGO_URL = "https://alchemiser.rwxt.org/android-chrome-512x512.png"
    LOGO_SIZE = "32px"

    @staticmethod
    def get_base_styles() -> str:
        """Get common CSS styles for email templates."""
        return """
        <style>
            @media (max-width: 600px) {
                .sm-w-full { width: 100% !important; }
                .sm-px-24 { padding-left: 24px !important; padding-right: 24px !important; }
            }
        </style>
        """

    @staticmethod
    def get_header(title: str, subtitle: str = "Quantitative Trading System") -> str:
        """Get HTML header section."""
        return f"""
        <tr>
            <td style="padding: 12px 24px; text-align: center; background: linear-gradient(135deg, #1F2937, #374151); border-radius: 8px 8px 0 0;">
                <img src="{BaseEmailTemplate.LOGO_URL}" alt="The Alchemiser Logo" style="width: {BaseEmailTemplate.LOGO_SIZE}; height: {BaseEmailTemplate.LOGO_SIZE}; margin-bottom: 8px;" />
                <h1 style="margin: 0; color: white; font-size: 18px; font-weight: 600;">
                    The Alchemiser
                </h1>
                <p style="margin: 2px 0 0 0; color: rgba(255,255,255,0.7); font-size: 12px;">
                    {subtitle}
                </p>
            </td>
        </tr>
        """

    @staticmethod
    def get_combined_header_status(
        title: str,
        status: str,
        status_color: str,
        status_emoji: str,
        timestamp: datetime | None = None,
    ) -> str:
        """Get combined header and status in one section."""
        timestamp = timestamp or datetime.now()

        return f"""
        <tr>
            <td style="padding: 16px 24px; text-align: center; background: linear-gradient(135deg, #1F2937, #374151); border-radius: 8px 8px 0 0;">
                <img src="{BaseEmailTemplate.LOGO_URL}" alt="The Alchemiser Logo" style="width: {BaseEmailTemplate.LOGO_SIZE}; height: {BaseEmailTemplate.LOGO_SIZE}; margin-bottom: 8px;" />
                <h1 style="margin: 0; color: white; font-size: 18px; font-weight: 600;">
                    The Alchemiser
                </h1>
                <p style="margin: 2px 0 6px 0; color: rgba(255,255,255,0.7); font-size: 12px;">
                    Quantitative Trading System
                </p>
                <div style="background: {status_color}; padding: 8px 16px; border-radius: 6px; margin-top: 8px;">
                    <h2 style="margin: 0; color: white; font-size: 16px; font-weight: 600;">
                        {title}
                    </h2>
                    <p style="margin: 2px 0 0 0; color: rgba(255,255,255,0.9); font-size: 12px;">
                        Status: {status} • {timestamp.strftime('%Y-%m-%d %H:%M:%S')}
                    </p>
                </div>
            </td>
        </tr>
        """

    @staticmethod
    def get_status_banner(
        title: str,
        status: str,
        status_color: str,
        status_emoji: str,
        timestamp: datetime | None = None,
    ) -> str:
        """Get HTML status banner section."""
        timestamp = timestamp or datetime.now()

        return f"""
        <tr>
            <td style="padding: 24px; background-color: {status_color}; text-align: center;">
                <h2 style="margin: 0; color: white; font-size: 24px; font-weight: 600;">
                    {status_emoji} {title}
                </h2>
                <p style="margin: 8px 0 0 0; color: rgba(255,255,255,0.9); font-size: 16px;">
                    Status: {status} • {timestamp.strftime('%Y-%m-%d %H:%M:%S')}
                </p>
            </td>
        </tr>
        """

    @staticmethod
    def get_footer() -> str:
        """Get HTML footer section."""
        return """
        <tr>
            <td style="padding: 24px; background-color: #1F2937; border-radius: 0 0 12px 12px; text-align: center;">
                <p style="margin: 0; color: #9CA3AF; font-size: 14px;">
                    Generated by The Alchemiser Quantitative Trading System
                </p>
                <p style="margin: 8px 0 0 0; color: #6B7280; font-size: 12px;">
                    Nuclear • TECL • Multi-Strategy
                </p>
            </td>
        </tr>
        """

    @staticmethod
    def wrap_content(content: str, title: str = "The Alchemiser") -> str:
        """Wrap content in base HTML email structure."""
        return f"""
        <!DOCTYPE html>
        <html lang="en" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
        <head>
            <meta charset="utf-8">
            <meta name="x-apple-disable-message-reformatting">
            <meta http-equiv="x-ua-compatible" content="ie=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <meta name="format-detection" content="telephone=no, date=no, address=no, email=no">
            <title>{title}</title>
            <!--[if mso]>
            <noscript>
                <xml>
                    <o:OfficeDocumentSettings>
                        <o:PixelsPerInch>96</o:PixelsPerInch>
                    </o:OfficeDocumentSettings>
                </xml>
            </noscript>
            <style>
                td,th,div,p,a,h1,h2,h3,h4,h5,h6 {{font-family: "Segoe UI", sans-serif; mso-line-height-rule: exactly;}}
            </style>
            <![endif]-->
            {BaseEmailTemplate.get_base_styles()}
        </head>
        <body style="margin: 0; width: 100%; padding: 0; word-break: break-word; -webkit-font-smoothing: antialiased; background-color: #F3F4F6;">
            <div style="display: none;">{title} - Quantitative Trading System Report</div>
            <div role="article" aria-roledescription="email" aria-label="{title}" lang="en">
                <table style="width: 100%; font-family: 'Segoe UI', ui-sans-serif, system-ui, -apple-system, 'Helvetica Neue', sans-serif;" cellpadding="0" cellspacing="0" role="presentation">
                    <tr>
                        <td align="center" style="background-color: #F3F4F6; padding: 24px 0;">
                            <table class="sm-w-full" style="width: 600px;" cellpadding="0" cellspacing="0" role="presentation">
                                {content}
                            </table>
                        </td>
                    </tr>
                </table>
            </div>
        </body>
        </html>
        """

    @staticmethod
    def create_section(title: str, content: str, margin: str = "24px 0") -> str:
        """Create a content section with title."""
        return f"""
        <div style="margin: {margin};">
            <h3 style="margin: 0 0 16px 0; color: #1F2937; font-size: 18px; font-weight: 600;">{title}</h3>
            {content}
        </div>
        """

    @staticmethod
    def create_alert_box(content: str, alert_type: str = "info") -> str:
        """Create an alert/notification box."""
        colors = {
            "success": {"bg": "#D1FAE5", "border": "#10B981", "text": "#065F46"},
            "error": {"bg": "#FEE2E2", "border": "#EF4444", "text": "#DC2626"},
            "warning": {"bg": "#FEF3C7", "border": "#F59E0B", "text": "#92400E"},
            "info": {"bg": "#DBEAFE", "border": "#3B82F6", "text": "#1E40AF"},
        }

        color_scheme = colors.get(alert_type, colors["info"])

        return f"""
        <div style="margin: 24px 0; padding: 16px; background-color: {color_scheme['bg']}; border-left: 4px solid {color_scheme['border']}; border-radius: 8px;">
            <p style="margin: 0; color: {color_scheme['text']};">{content}</p>
        </div>
        """

    @staticmethod
    def create_table(headers: list[str], rows: list[list[str]], table_id: str = "") -> str:
        """Create a responsive table."""
        header_html = "".join(
            [
                f"<th style='padding: 12px; text-align: left; font-weight: 600; color: #374151; border-bottom: 1px solid #E5E7EB;'>{header}</th>"
                for header in headers
            ]
        )

        rows_html = ""
        for row in rows:
            row_html = "".join(
                [
                    f"<td style='padding: 8px 12px; border-bottom: 1px solid #E5E7EB;'>{cell}</td>"
                    for cell in row
                ]
            )
            rows_html += f"<tr>{row_html}</tr>"

        return f"""
        <table id="{table_id}" style="width: 100%; border-collapse: collapse; background-color: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
            <thead>
                <tr style="background-color: #F9FAFB;">
                    {header_html}
                </tr>
            </thead>
            <tbody>
                {rows_html}
            </tbody>
        </table>
        """
