#!/bin/bash
# Shared Module Cleanup Script
# Generated by Shared Module Audit

set -e  # Exit on any error

echo "Starting shared module cleanup..."
echo "Creating backup..."

# Create backup
backup_dir="/tmp/shared_module_backup_$(date +%Y%m%d_%H%M%S)"
cp -r the_alchemiser/shared "$backup_dir"
echo "Backup created at: $backup_dir"

# Function to safely remove a file
safe_remove() {
    local file="$1"
    if [ -f "the_alchemiser/shared/$file" ]; then
        echo "Removing: $file"
        rm "the_alchemiser/shared/$file"
    else
        echo "File not found: $file"
    fi
}

echo ""
echo "Phase 1: Removing test/demo files..."
safe_remove "simple_dto_test.py"
safe_remove "dto_communication_demo.py"

echo ""
echo "Phase 1 complete!"
echo "Run 'git status' to review changes"
echo "Run 'make test' to verify nothing is broken"
echo ""
echo "To restore from backup if needed:"
echo "rm -rf the_alchemiser/shared && cp -r $backup_dir the_alchemiser/shared"
