# Logging configuration
logging:
  level: "INFO"
  nuclear_alerts_log: "s3://the-alchemiser-s3/nuclear_alerts.log"
  nuclear_alerts_json: "s3://the-alchemiser-s3/nuclear_alerts.json"
  multi_strategy_alerts: "s3://the-alchemiser-s3/multi_strategy_alerts.json"
  multi_strategy_log: "s3://the-alchemiser-s3/multi_strategy_execution.log"
  strategy_positions: "s3://the-alchemiser-s3/strategy_positions.json"
  strategy_orders: "s3://the-alchemiser-s3/strategy_orders.json"
  strategy_positions_detailed: "s3://the-alchemiser-s3/strategy_positions_detailed.json"
  tecl_strategy_log: "s3://the-alchemiser-s3/tecl_strategy.log"
  alpaca_log: "s3://the-alchemiser-s3/alpaca_trader.log"
  alpaca_trades_json: "s3://the-alchemiser-s3/alpaca_trades.json"

# Alpaca configuration
alpaca:
  # api_key and api_secret loaded from .env
  endpoint: "https://api.alpaca.markets"
  paper_endpoint: "https://paper-api.alpaca.markets/v2"
  cash_reserve_pct: 0.05

# Data configuration
data:
  cache_duration: 300
  default_symbol: "AAPL"
