# Logging configuration
logging:
  level: "INFO"
  nuclear_alerts_log: "/tmp/nuclear_alerts.log"
  nuclear_alerts_json: "/tmp/nuclear_alerts.json"
  multi_strategy_alerts: "/tmp/multi_strategy_alerts.json"
  multi_strategy_log: "/tmp/multi_strategy_execution.log"
  strategy_positions: "/tmp/strategy_positions.json"
  tecl_strategy_log: "/tmp/tecl_strategy.log"
  alpaca_log: "/tmp/alpaca_trader.log"
  alpaca_trades_json: "/tmp/alpaca_trades.json"

# Alpaca configuration
alpaca:
  # api_key and api_secret loaded from .env
  endpoint: "https://api.alpaca.markets"
  paper_endpoint: "https://paper-api.alpaca.markets/v2"
  cash_reserve_pct: 0.05

# Data configuration
data:
  cache_duration: 300
  default_symbol: "AAPL"
