# Logging configuration
logging:
  level: "INFO"
  nuclear_alerts_log: "data/logs/nuclear_alerts.log"
  nuclear_alerts_json: "data/logs/nuclear_alerts.json"
  alpaca_log: "data/logs/alpaca_trader.log"
  alpaca_trades_json: "data/logs/alpaca_trades.json"

# Alpaca configuration
alpaca:
  # api_key and api_secret loaded from .env
  endpoint: "https://api.alpaca.markets"
  paper_endpoint: "https://paper-api.alpaca.markets/v2"
  cash_reserve_pct: 0.05

# Data configuration
data:
  cache_duration: 300
  default_symbol: "AAPL"
