"""Shared schemas module.

Business Unit: shared | Status: current

Common schema definitions used across modules.
"""

from .accounts import (
    AccountMetrics,
    __all__ = [
        "AccountMetrics",
        "AccountSummary",
        "AllocationComparison",
        "AssetInfo",
        "AssetType",
        "ASTNode",
        "BuyingPowerResult",
        "Configuration",
        "ConfigurationDTO",
        "ConsolidatedPortfolio",
        "create_failure_result",
        "create_success_result",
        "EnrichedAccountSummaryView",
        "Error",
        "ErrorContextData",
        "ErrorDTO",
        "ErrorDetailInfo",
        "ErrorNotificationData",
        "ErrorReportSummary",
        "ErrorSummaryData",
        "ExecutedOrder",
        "ExecutionReport",
        "ExecutionReportDTO",
        "ExecutionResult",
        "ExecutionSummary",
        "IndicatorRequest",
        "LambdaEvent",
        "Lot",
        "MarketBar",
        "MarketData",
        "MarketDataDTO",
        "MarketStatusResult",
        "MultiStrategyExecutionResult",
        "MultiStrategySummary",
        "MultiSymbolQuotesResult",
        "OrderExecutionResult",
        "OrderRequest",
        "OrderRequestDTO",
        "OrderResultSummary",
        "OrderResultSummaryDTO",
        "PerformanceSummary",
        "PortfolioAllocationResult",
        "PortfolioMetrics",
        "PortfolioState",
        "Position",
        "PositionDTO",
        "PriceHistoryResult",
        "PriceResult",
        "RebalancePlan",
        "RebalancePlanItem",
        "Result",
        "RiskMetricsResult",
        "SpreadAnalysisResult",
        "StrategyAllocation",
        "StrategySignal",
        "StrategySignalDTO",
        "TechnicalIndicator",
        "Trace",
        "TraceEntry",
        "TraceEntryDTO",
        "TradeEligibilityResult",
        "TradeLedgerEntry",
        "TradeLedgerQuery",
        "TradeRunResult",
        "TradeSide",
        "WebSocketResult",
        "WebSocketStatus",
    ]
    "Configuration",
    "ConfigurationDTO",
    "Error",
    "ErrorDTO",
    "MultiStrategyExecutionResult",
    "MultiStrategySummary",
    # Asset and broker schemas
    "AssetInfo",
    "AssetType",
    "BuyingPowerResult",
    "OrderExecutionResult",
    "WebSocketResult",
    "WebSocketStatus",
    # Portfolio schemas
    "ConsolidatedPortfolio",
    "EnrichedAccountSummaryView",
    "PortfolioAllocationResult",
    "PortfolioMetrics",
    "PortfolioState",
    "Position",
    "PositionDTO",
    "RiskMetricsResult",
    "TradeEligibilityResult",
    # Error schemas
    "ErrorContextData",
    "ErrorDetailInfo",
    "ErrorNotificationData",
    "ErrorReportSummary",
    "ErrorSummaryData",
    # Execution schemas
    "ExecutedOrder",
    "ExecutionReport",
    "ExecutionReportDTO",
    "ExecutionResult",
    "ExecutionSummary",
    "OrderResultSummary",
    "OrderResultSummaryDTO",
    # Strategy schemas
    "IndicatorRequest",
    "StrategyAllocation",
    "StrategySignal",
    "StrategySignalDTO",
    "TechnicalIndicator",
    # Event and infrastructure schemas
    "LambdaEvent",
    # Trading schemas
    "Lot",
    "PerformanceSummary",
    "TradeLedgerEntry",
    "TradeLedgerQuery",
    "TradeRunResult",
    "TradeSide",
    # Market data schemas
    "MarketBar",
    "MarketData",
    "MarketDataDTO",
    "MarketStatusResult",
    "MultiSymbolQuotesResult",
    "PriceHistoryResult",
    "PriceResult",
    "SpreadAnalysisResult",
    # Base schemas
    "Result",
    # Trace schemas
    "Trace",
    "TraceEntry",
    "TraceEntryDTO",
    # Factory functions
    "create_failure_result",
    "create_success_result",
]
