"""Business Unit: dashboard | Status: current.

Tearsheets page -- renders quantstats HTML tearsheets inline.

Supports per-strategy and account-level tearsheets generated by
``scripts/generate_tearsheets.py`` and stored in S3 under
``strategy-reports/{name}/tearsheet.html``.
"""

from __future__ import annotations

import streamlit as st
import streamlit.components.v1 as components

from components.styles import inject_styles
from components.ui import section_header
from data import strategy as sda
from settings import get_dashboard_settings


def show() -> None:
    """Display the Tearsheets page."""
    inject_styles()

    st.title("Tearsheets")
    st.caption("Quantstats HTML tearsheets -- generated locally and stored in S3")

    settings = get_dashboard_settings()
    if not settings.has_aws_credentials():
        st.error(
            "AWS credentials not configured. "
            "Set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in "
            "Streamlit secrets or environment variables."
        )
        return

    available = sda.get_available_tearsheets()
    if not available:
        st.info(
            "No tearsheets found in S3. Generate them with:\n\n"
            "```\npython scripts/generate_tearsheets.py --stage dev\n"
            "python scripts/generate_tearsheets.py --stage dev --account\n```"
        )
        return

    # Split into strategy vs account entries
    has_account = "_account" in available
    strategy_names = [n for n in available if n != "_account"]

    # Mode selector
    mode_options = []
    if strategy_names:
        mode_options.append("Strategy")
    if has_account:
        mode_options.append("Account")

    if len(mode_options) > 1:
        mode = st.radio("Tearsheet type", mode_options, horizontal=True)
    elif mode_options:
        mode = mode_options[0]
    else:
        st.info("No tearsheets available.")
        return

    # Resolve which tearsheet to load
    selected_name: str | None = None

    if mode == "Account":
        selected_name = "_account"
    else:
        metadata = sda.get_all_strategy_metadata()
        display_map = {
            name: metadata.get(name, {}).get("display_name", name)
            for name in strategy_names
        }
        selected_name = st.selectbox(
            "Select strategy",
            options=strategy_names,
            format_func=lambda x: display_map.get(x, x),
        )

    if not selected_name:
        return

    # Load and render the tearsheet HTML
    section_header(
        "Account Tearsheet" if selected_name == "_account" else f"{selected_name} Tearsheet"
    )

    with st.spinner("Loading tearsheet..."):
        html = sda.get_tearsheet_html(selected_name)

    if html is None:
        st.warning(f"No tearsheet found for '{selected_name}'.")
        return

    components.html(html, height=800, scrolling=True)

    st.caption(
        "Tearsheets are generated locally via "
        "`python scripts/generate_tearsheets.py` and uploaded to S3."
    )
