"""Data transfer objects.

DEPRECATED: This module is deprecated. Use `the_alchemiser.shared.schemas` instead.
This module will be removed in a future version.
"""

from __future__ import annotations

import warnings

# Re-export everything from schemas for backward compatibility
from the_alchemiser.shared.schemas import (
    AssetInfo,
    AssetInfoDTO,
    AssetType,
    Configuration,
    ConfigurationDTO,
    Error,
    ErrorDTO,
    ExecutedOrder,
    ExecutedOrderDTO,
    ExecutionReport,
    ExecutionReportDTO,
    ExecutionSummary,
    ExecutionSummaryDTO,
    LambdaEvent,
    LambdaEventDTO,
    Lot,
    MarketBar,
    MarketBarDTO,
    MarketData,
    MarketDataDTO,
    OrderRequest,
    OrderRequestDTO,
    OrderResultSummary,
    OrderResultSummaryDTO,
    PerformanceSummary,
    PortfolioMetrics,
    PortfolioMetricsDTO,
    PortfolioState,
    PortfolioStateDTO,
    Position,
    PositionDTO,
    RebalancePlan,
    RebalancePlanDTO,
    RebalancePlanItem,
    RebalancePlanItemDTO,
    StrategyAllocation,
    StrategyAllocationDTO,
    StrategySignal,
    StrategySignalDTO,
    TechnicalIndicator,
    TechnicalIndicatorDTO,
    TradeLedgerEntry,
    TradeLedgerQuery,
    TradeRunResult,
    TradeRunResultDTO,
    TradeSide,
)

# Emit deprecation warning on first import
warnings.warn(
    "`the_alchemiser.shared.dto` is deprecated; use `the_alchemiser.shared.schemas`.",
    DeprecationWarning,
    stacklevel=2,
)

# Keep old __all__ for backward compatibility - it will be imported from schemas
__all__ = [
    "AssetInfo",
    "AssetInfoDTO",
    "AssetType",
    "Configuration",
    "ConfigurationDTO",
    "Error",
    "ErrorDTO",
    "ExecutedOrder",
    "ExecutedOrderDTO",
    "ExecutionReport",
    "ExecutionReportDTO",
    "ExecutionSummary",
    "ExecutionSummaryDTO",
    "LambdaEvent",
    "LambdaEventDTO",
    "Lot",
    "MarketBar",
    "MarketBarDTO",
    "MarketData",
    "MarketDataDTO",
    "OrderRequest",
    "OrderRequestDTO",
    "OrderResultSummary",
    "OrderResultSummaryDTO",
    "PerformanceSummary",
    "PortfolioMetrics",
    "PortfolioMetricsDTO",
    "PortfolioState",
    "PortfolioStateDTO",
    "Position",
    "PositionDTO",
    "RebalancePlan",
    "RebalancePlanDTO",
    "RebalancePlanItem",
    "RebalancePlanItemDTO",
    "StrategyAllocation",
    "StrategyAllocationDTO",
    "StrategySignal",
    "StrategySignalDTO",
    "TechnicalIndicator",
    "TechnicalIndicatorDTO",
    "TradeLedgerEntry",
    "TradeLedgerQuery",
    "TradeRunResult",
    "TradeRunResultDTO",
    "TradeSide",
]
