(defsymphony
 "Ultra Long Term"
 {:asset-class "EQUITIES", :rebalance-frequency :daily}
 (weight-equal
  [(asset "QBTS" "D-Wave Quantum Inc.")
   (asset "QUBT" "Quantum Computing Inc.")
   (asset "RGTI" "Rigetti Computing, Inc.")
   (asset "ARQQ" "Arqit Quantum Inc.")
   (asset "IONQ" "IonQ, Inc.")
   (asset "QMCO" "Quantum Corporation")
   (asset "PLTR" "Palantir Technologies Inc. Class A")
   (asset "SOUN" "SoundHound AI, Inc Class A")
   (asset "AVGO" "Broadcom Inc.")
   (asset "NVDA" "NVIDIA Corporation")
   (asset "ZS" "Zscaler, Inc.")
   (asset "CEG" "Constellation Energy Corporation")
   (asset "NNE" "Nano Nuclear Energy Inc.")
   (asset "SMR" "NuScale Power Corporation Class A")
   (asset "BE" "Bloom Energy Corporation Class A")
   (asset "CCJ" "Cameco Corporation")
   (asset "IREN" "IREN Limited")
   (asset "UEC" "Uranium Energy Corp.")
   (asset "RKLB" "Rocket Lab USA, Inc.")
   (asset "SIDU" "Sidus Space, Inc. Class A")
   (asset "ARM" "ARM Holdings PLC ADR")
   (asset "MARA" "MARA Holdings, Inc.")
   (asset "CRM" "Salesforce, Inc.")
   (asset "OKLO" "Oklo Inc. Class A")
   (asset "QSI" "Quantum-Si Incorporated Class A")
   (asset "APLD" "Applied Digital Corporation")
   (asset "ACHR" "Archer Aviation Inc Class A")
   (asset "FFAI" nil)
   (asset "JOBY" "Joby Aviation, Inc.")
   (asset "WULF" "TeraWulf Inc.")
   (asset "FTNT" "Fortinet, Inc.")
   (asset "PLUG" "Plug Power Inc.")
   (asset "EVLV" "Evolv Technologies Holdings, Inc.")
   (asset "VNOM" "Viper Energy Inc - Ordinary Shares - Class A")
   (asset "SNOW" "Snowflake Inc - Ordinary Shares - Class A")
   (asset "VRSN" "Verisign Inc.")
   (asset "LAES" "SEALSQ Corp")
   (asset "BBAI" "BigBear.ai Holdings Inc")
   (asset "MRVL" "Marvell Technology Inc")
   (asset "NLSP" "NLS Pharmaceutics Ltd")
   (asset
    "RXRX"
    "Recursion Pharmaceuticals Inc - Ordinary Shares - Class A")
   (asset "ABSI" "Absci Corp")
   (asset "AEHR" "Aehr Test Systems")
   (asset "RZLV" "Rezolve AI Ltd")
   (asset "SES" "SES AI Corporation - Ordinary Shares - Class A")
   (asset "X" "United States Steel Corp.")
   (asset "SERV" "Serve Robotics Inc")
   (asset "QS" "QuantumScape Corp - Ordinary Shares - Class A")
   (asset "CRNC" "Cerence Inc")
   (asset "WKEY" "WISeKey International Holding Ltd - ADR")
   (asset "MSFT" "Microsoft Corporation")
   (asset "AMZN" "Amazon.com Inc.")
   (asset "TEM" "Tempus AI Inc. - Ordinary Shares - Class A")
   (asset
    "IBKR"
    "Interactive Brokers Group Inc - Ordinary Shares - Class A")
   (asset "ORCL" "Oracle Corp.")
   (asset "APP" "Applovin Corp - Ordinary Shares - Class A")
   (asset "NFLX" "Netflix Inc.")
   (asset "RIOT" "Riot Platforms Inc")
   (asset "HOOD" "Robinhood Markets Inc - Ordinary Shares - Class A")
   (asset "CORZ" "Core Scientific Inc - Ordinary Shares - New")]))
