"""Business Unit: shared | Status: current.

Options hedging constants and configuration.
"""

from __future__ import annotations

from .hedge_config import (
    # Thresholds
    CRITICAL_DTE_THRESHOLD,
    DEFAULT_ETF_PRICE_FALLBACK,
    DEFAULT_ETF_PRICES,
    HEDGE_ETFS,
    LIMIT_PRICE_DISCOUNT_FACTOR,
    LIQUIDITY_FILTERS,
    MAX_ANNUAL_PREMIUM_SPEND_PCT,
    # Marketability algorithm parameters
    MAX_DAILY_SLIPPAGE_PCT,
    MAX_EXISTING_HEDGE_COUNT,
    MAX_FILL_ATTEMPTS,
    MAX_FILL_TIME_SECONDS,
    MAX_SINGLE_POSITION_PCT,
    MAX_SLIPPAGE_PER_TRADE_CLOSE,
    MAX_SLIPPAGE_PER_TRADE_OPEN,
    MIN_EXPOSURE_RATIO,
    MIN_NAV_THRESHOLD,
    ORDER_POLL_INTERVAL_SECONDS,
    PRICE_STEP_PCT_CALM,
    PRICE_STEP_PCT_HIGH_IV,
    PRICE_UPDATE_INTERVAL_SECONDS,
    QQQ_PREFERENCE_THRESHOLD,
    RICH_IV_THRESHOLD,
    # FR-8: Enhanced roll trigger thresholds
    SKEW_BASELINE_WINDOW,
    SKEW_CHANGE_THRESHOLD,
    SMOOTHING_HEDGE_TEMPLATE,
    SPREAD_LONG_DELTA_THRESHOLD,
    SPREAD_SHORT_DELTA_THRESHOLD,
    SPREAD_WIDTH_VALUE_THRESHOLD,
    STRIKE_MAX_OTM_RATIO,
    STRIKE_MIN_OTM_RATIO,
    TAIL_DELTA_DRIFT_THRESHOLD,
    TAIL_EXTRINSIC_DECAY_THRESHOLD,
    TAIL_HEDGE_TEMPLATE,
    TARGET_ANNUAL_PREMIUM_SPEND_MAX_PCT,
    TARGET_ANNUAL_PREMIUM_SPEND_MIN_PCT,
    VIX_HIGH_THRESHOLD,
    VIX_LOW_THRESHOLD,
    VIX_PROXY_SCALE_FACTOR,
    VIX_PROXY_SYMBOL,
    # Dataclasses
    HedgeETF,
    LiquidityFilters,
    SmoothingHedgeTemplate,
    TailHedgeTemplate,
    # Functions
    apply_rich_iv_adjustment,
    calculate_annual_drag,
    check_annual_spend_cap,
    get_budget_rate_for_vix,
    get_exposure_multiplier,
    should_reduce_hedge_intensity,
)
from .sector_mapping import (
    TICKER_SECTOR_MAP,
    get_hedge_etf,
)

__all__ = [
    "CRITICAL_DTE_THRESHOLD",
    "DEFAULT_ETF_PRICES",
    "DEFAULT_ETF_PRICE_FALLBACK",
    "HEDGE_ETFS",
    "LIMIT_PRICE_DISCOUNT_FACTOR",
    "LIQUIDITY_FILTERS",
    "MAX_ANNUAL_PREMIUM_SPEND_PCT",
    "MAX_DAILY_SLIPPAGE_PCT",
    "MAX_EXISTING_HEDGE_COUNT",
    "MAX_FILL_ATTEMPTS",
    "MAX_FILL_TIME_SECONDS",
    "MAX_SINGLE_POSITION_PCT",
    "MAX_SLIPPAGE_PER_TRADE_CLOSE",
    "MAX_SLIPPAGE_PER_TRADE_OPEN",
    "MIN_EXPOSURE_RATIO",
    "MIN_NAV_THRESHOLD",
    "ORDER_POLL_INTERVAL_SECONDS",
    "PRICE_STEP_PCT_CALM",
    "PRICE_STEP_PCT_HIGH_IV",
    "PRICE_UPDATE_INTERVAL_SECONDS",
    "QQQ_PREFERENCE_THRESHOLD",
    "RICH_IV_THRESHOLD",
    # FR-8: Enhanced roll trigger thresholds
    "SKEW_BASELINE_WINDOW",
    "SKEW_CHANGE_THRESHOLD",
    "SMOOTHING_HEDGE_TEMPLATE",
    "SPREAD_LONG_DELTA_THRESHOLD",
    "SPREAD_SHORT_DELTA_THRESHOLD",
    "SPREAD_WIDTH_VALUE_THRESHOLD",
    "STRIKE_MAX_OTM_RATIO",
    "STRIKE_MIN_OTM_RATIO",
    "TAIL_DELTA_DRIFT_THRESHOLD",
    "TAIL_EXTRINSIC_DECAY_THRESHOLD",
    "TAIL_HEDGE_TEMPLATE",
    "TARGET_ANNUAL_PREMIUM_SPEND_MAX_PCT",
    "TARGET_ANNUAL_PREMIUM_SPEND_MIN_PCT",
    "TICKER_SECTOR_MAP",
    "VIX_HIGH_THRESHOLD",
    "VIX_LOW_THRESHOLD",
    "VIX_PROXY_SCALE_FACTOR",
    "VIX_PROXY_SYMBOL",
    "HedgeETF",
    "LiquidityFilters",
    "SmoothingHedgeTemplate",
    "TailHedgeTemplate",
    "apply_rich_iv_adjustment",
    "calculate_annual_drag",
    "check_annual_spend_cap",
    "get_budget_rate_for_vix",
    "get_exposure_multiplier",
    "get_hedge_etf",
    "should_reduce_hedge_intensity",
]
