"""Business Unit: backtest | Status: current.

PDF report generation for backtest results.

Uses matplotlib's PDF backend to create multi-page PDF reports with
charts and summary tables.
"""

from __future__ import annotations

from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING

import matplotlib  # type: ignore[import-not-found]

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # type: ignore[import-not-found]
from matplotlib.backends.backend_pdf import PdfPages  # type: ignore[import-not-found]

from the_alchemiser.backtest_v2.reporting.charts import (
    create_drawdown_chart,
    create_equity_chart,
    create_monthly_returns_heatmap,
    create_rolling_sharpe_chart,
    create_trade_distribution_chart,
)

if TYPE_CHECKING:
    from the_alchemiser.backtest_v2.core.result import BacktestResult


def _format_pct(value: float) -> str:
    """Format a decimal as percentage string."""
    return f"{value * 100:+.2f}%"


def _format_ratio(value: float) -> str:
    """Format a ratio."""
    if value >= 999:
        return "∞"
    return f"{value:.2f}"


def _create_summary_page(result: BacktestResult) -> plt.Figure:
    """Create the summary page with metrics table.

    Args:
        result: Backtest result

    Returns:
        Matplotlib figure

    """
    fig = plt.figure(figsize=(11, 8.5))

    # Title
    config = result.config_summary
    strategy_path = str(config.get("strategy_path", "N/A"))
    strategy_name = Path(strategy_path).stem if strategy_path != "N/A" else "Backtest"

    fig.suptitle(
        f"Backtest Report: {strategy_name}",
        fontsize=18,
        fontweight="bold",
        y=0.98,
    )

    # Subtitle with dates
    fig.text(
        0.5,
        0.93,
        f"{config.get('start_date', 'N/A')} to {config.get('end_date', 'N/A')}",
        ha="center",
        fontsize=12,
        color="gray",
    )

    # Create two columns of metrics
    ax = fig.add_axes([0.1, 0.1, 0.8, 0.75])
    ax.axis("off")

    # Left column - Performance Metrics
    left_metrics = [
        ("Configuration", ""),
        ("Strategy", strategy_path),
        ("Initial Capital", f"${float(str(config.get('initial_capital', 0))):,.2f}"),
        ("Trading Days", str(config.get("trading_days", 0))),
        ("Total Trades", str(config.get("total_trades", 0))),
        ("Slippage", f"{config.get('slippage_bps', 0)} bps"),
        ("", ""),
        ("Performance Metrics", ""),
        ("Total Return", _format_pct(float(result.metrics.total_return))),
        ("CAGR", _format_pct(float(result.metrics.cagr))),
        ("Sharpe Ratio", _format_ratio(result.metrics.sharpe_ratio)),
        ("Sortino Ratio", _format_ratio(result.metrics.sortino_ratio)),
        ("Max Drawdown", _format_pct(-float(result.metrics.max_drawdown))),
        ("Max DD Duration", f"{result.metrics.max_drawdown_duration_days} days"),
        ("Volatility (Ann.)", _format_pct(float(result.metrics.volatility))),
        ("Calmar Ratio", _format_ratio(result.metrics.calmar_ratio)),
    ]

    # Right column - Trading Stats & Benchmark
    right_metrics = [
        ("Trading Statistics", ""),
        ("Win Rate", _format_pct(result.metrics.win_rate)),
        ("Profit Factor", _format_ratio(result.metrics.profit_factor)),
        ("Alpha vs SPY", _format_pct(result.alpha)),
        ("", ""),
        ("Benchmark (SPY)", ""),
        ("Benchmark Return", _format_pct(float(result.benchmark_metrics.total_return))),
        ("Benchmark CAGR", _format_pct(float(result.benchmark_metrics.cagr))),
        ("Benchmark Sharpe", _format_ratio(result.benchmark_metrics.sharpe_ratio)),
        ("Benchmark Max DD", _format_pct(-float(result.benchmark_metrics.max_drawdown))),
        ("", ""),
        ("Errors", str(len(result.errors))),
    ]

    # Draw left column
    y_start = 0.85
    y_step = 0.045
    for i, (label, value) in enumerate(left_metrics):
        y = y_start - i * y_step
        if value == "":  # Section header
            ax.text(0.05, y, label, fontsize=12, fontweight="bold", transform=ax.transAxes)
        else:
            ax.text(0.05, y, label, fontsize=10, transform=ax.transAxes)
            ax.text(0.35, y, value, fontsize=10, transform=ax.transAxes)

    # Draw right column
    for i, (label, value) in enumerate(right_metrics):
        y = y_start - i * y_step
        if value == "":  # Section header
            ax.text(0.55, y, label, fontsize=12, fontweight="bold", transform=ax.transAxes)
        else:
            ax.text(0.55, y, label, fontsize=10, transform=ax.transAxes)
            ax.text(0.85, y, value, fontsize=10, transform=ax.transAxes)

    # Footer
    fig.text(
        0.5,
        0.02,
        f"Generated by The Alchemiser Backtest Engine | {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}",
        ha="center",
        fontsize=8,
        color="gray",
    )

    return fig


def _create_chart_page(
    result: BacktestResult,
    chart_func: Callable[..., str | bytes],
    title: str,
    **kwargs: object,
) -> plt.Figure:
    """Create a page with a single chart.

    Args:
        result: Backtest result
        chart_func: Chart generation function
        title: Page title
        **kwargs: Additional kwargs for chart function

    Returns:
        Matplotlib figure

    """
    # Get chart as bytes
    chart_result = chart_func(result, as_base64=False, **kwargs)
    chart_bytes = chart_result if isinstance(chart_result, bytes) else chart_result.encode()

    # Create figure and embed image
    fig = plt.figure(figsize=(11, 8.5))
    fig.suptitle(title, fontsize=16, fontweight="bold", y=0.98)

    # Load image from bytes
    import io

    from PIL import Image

    img = Image.open(io.BytesIO(chart_bytes))

    ax = fig.add_axes([0.05, 0.05, 0.9, 0.85])
    ax.imshow(img)
    ax.axis("off")

    return fig


def _create_trades_page(result: BacktestResult, page_num: int = 0) -> plt.Figure | None:
    """Create a page with trades table.

    Args:
        result: Backtest result
        page_num: Page number (for pagination, 50 trades per page)

    Returns:
        Matplotlib figure or None if no trades

    """
    trades_per_page = 40
    start_idx = page_num * trades_per_page
    end_idx = start_idx + trades_per_page

    trades = result.trades[start_idx:end_idx] if result.trades else []
    if not trades:
        return None

    fig = plt.figure(figsize=(11, 8.5))
    fig.suptitle(
        f"Trade Log (Page {page_num + 1})",
        fontsize=16,
        fontweight="bold",
        y=0.98,
    )

    ax = fig.add_axes([0.05, 0.05, 0.9, 0.88])
    ax.axis("off")

    # Table data
    headers = ["Date", "Symbol", "Action", "Shares", "Price", "Value", "Commission"]
    cell_data = []
    for trade in trades:
        row = [
            trade.date.strftime("%Y-%m-%d"),
            trade.symbol,
            trade.action,
            f"{float(trade.shares):,.0f}",
            f"${float(trade.price):,.2f}",
            f"${float(trade.value):,.2f}",
            f"${float(trade.commission):,.2f}",
        ]
        cell_data.append(row)

    # Create table
    table = ax.table(
        cellText=cell_data,
        colLabels=headers,
        loc="upper center",
        cellLoc="center",
        colWidths=[0.12, 0.1, 0.08, 0.12, 0.14, 0.14, 0.12],
    )
    table.auto_set_font_size(auto=False)
    table.set_fontsize(8)
    table.scale(1.2, 1.5)

    # Style header
    for i in range(len(headers)):
        table[(0, i)].set_facecolor("#2E86AB")
        table[(0, i)].set_text_props(color="white", fontweight="bold")

    # Alternate row colors
    for i in range(1, len(cell_data) + 1):
        for j in range(len(headers)):
            if i % 2 == 0:
                table[(i, j)].set_facecolor("#f8f9fa")

    return fig


def generate_pdf_report(
    result: BacktestResult,
    output_path: Path | str,
) -> Path:
    """Generate PDF report from backtest results.

    Creates a multi-page PDF with:
    - Summary page with all metrics
    - Equity curve chart
    - Drawdown chart
    - Monthly returns heatmap
    - Rolling Sharpe chart
    - Trade distribution chart
    - Trade log tables (paginated)

    Args:
        result: Backtest result object
        output_path: Path to save the PDF file

    Returns:
        Path to the generated PDF

    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Check if PIL is available for chart embedding
    try:
        from PIL import Image  # noqa: F401

        use_embedded_charts = True
    except ImportError:
        use_embedded_charts = False

    with PdfPages(str(output_path)) as pdf:
        # Page 1: Summary
        summary_fig = _create_summary_page(result)
        pdf.savefig(summary_fig, bbox_inches="tight")
        plt.close(summary_fig)

        if use_embedded_charts:
            # Page 2: Equity Curve
            equity_fig = _create_chart_page(result, create_equity_chart, "Equity Curve")
            pdf.savefig(equity_fig, bbox_inches="tight")
            plt.close(equity_fig)

            # Page 3: Drawdown
            dd_fig = _create_chart_page(result, create_drawdown_chart, "Drawdown Analysis")
            pdf.savefig(dd_fig, bbox_inches="tight")
            plt.close(dd_fig)

            # Page 4: Monthly Returns
            monthly_fig = _create_chart_page(
                result, create_monthly_returns_heatmap, "Monthly Returns Heatmap"
            )
            pdf.savefig(monthly_fig, bbox_inches="tight")
            plt.close(monthly_fig)

            # Page 5: Rolling Sharpe
            sharpe_fig = _create_chart_page(
                result, create_rolling_sharpe_chart, "Rolling Sharpe Ratio"
            )
            pdf.savefig(sharpe_fig, bbox_inches="tight")
            plt.close(sharpe_fig)

            # Page 6: Trade Distribution
            dist_fig = _create_chart_page(
                result, create_trade_distribution_chart, "Trade Value Distribution"
            )
            pdf.savefig(dist_fig, bbox_inches="tight")
            plt.close(dist_fig)
        else:
            # Generate charts directly (without embedding)
            # Equity curve
            equity_bytes = create_equity_chart(result, as_base64=False)
            if isinstance(equity_bytes, bytes):
                _save_bytes_to_pdf_page(pdf, equity_bytes, "Equity Curve")

            # Other charts...
            dd_bytes = create_drawdown_chart(result, as_base64=False)
            if isinstance(dd_bytes, bytes):
                _save_bytes_to_pdf_page(pdf, dd_bytes, "Drawdown Analysis")

        # Trade log pages
        page_num = 0
        while True:
            trades_fig = _create_trades_page(result, page_num)
            if trades_fig is None:
                break
            pdf.savefig(trades_fig, bbox_inches="tight")
            plt.close(trades_fig)
            page_num += 1
            if page_num > 10:  # Limit to 10 pages of trades
                break

    return output_path


def _save_bytes_to_pdf_page(pdf: PdfPages, img_bytes: bytes, title: str) -> None:
    """Save image bytes directly to PDF page (fallback without PIL)."""
    import tempfile

    # Write to temp file and read back
    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
        tmp.write(img_bytes)
        tmp_path = tmp.name

    fig = plt.figure(figsize=(11, 8.5))
    fig.suptitle(title, fontsize=16, fontweight="bold", y=0.98)

    ax = fig.add_axes([0.05, 0.05, 0.9, 0.85])
    img = plt.imread(tmp_path)
    ax.imshow(img)
    ax.axis("off")

    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)

    # Clean up temp file
    Path(tmp_path).unlink(missing_ok=True)
