# Logging configuration
logging:
  level: "INFO"

# Alpaca configuration
alpaca:
  # api_key and api_secret loaded from .env
  endpoint: "https://api.alpaca.markets/v2"
  paper_endpoint: "https://paper-api.alpaca.markets/v2"
  cash_reserve_pct: 0.05
  slippage_bps: 5

# AWS/Lambda deployment
aws:
  account_id: "211125653762"
  region: "eu-west-2"
  repo_name: "the-alchemiser"
  lambda_arn: "arn:aws:lambda:eu-west-2:211125653762:function:the-alchemiser"
  image_tag: "latest"

# Alert settings
alerts:
  alert_config_s3: "s3://the-alchemiser-s3/alert_config.json"
  cooldown_minutes: 30

# Secrets Manager
secrets_manager:
  region_name: "eu-west-2"
  secret_name: "nuclear-secrets"

# Strategy defaults
strategy:
  default_strategy_allocations:
    nuclear: 0.3
    tecl: 0.6
    klm: 0.1
  poll_timeout: 30
  poll_interval: 2.0

# Email notification configuration
email:
  smtp_server: "smtp.mail.me.com"
  smtp_port: 587
  from_email: "josh@rwxt.org"
  to_email: "josh@rwxt.org" # Optional, defaults to from_email

# Data configuration (preserved from previous config)
data:
  cache_duration: 300
  default_symbol: "AAPL"
