# Logging configuration
logging:
  level: "INFO"
  multi_strategy_log: "s3://the-alchemiser-s3/multi_strategy_execution.log"
  alpaca_log: "s3://the-alchemiser-s3/alpaca_trader.log"

# Alpaca configuration
alpaca:
  # api_key and api_secret loaded from .env
  endpoint: "https://api.alpaca.markets"
  paper_endpoint: "https://paper-api.alpaca.markets/v2"
  cash_reserve_pct: 0.05

# Data configuration
data:
  cache_duration: 300
  default_symbol: "AAPL"
