# Logging configuration
logging:
  level: "INFO"

# Alpaca configuration
alpaca:
  # api_key and api_secret loaded from .env
  endpoint: "https://api.alpaca.markets/v2"
  paper_endpoint: "https://paper-api.alpaca.markets/v2"
  cash_reserve_pct: 0.05
  slippage_bps: 5

# AWS/Lambda deployment
aws:
  account_id: "211125653762"
  region: "eu-west-2"
  repo_name: "the-alchemiser"
  lambda_arn: "arn:aws:lambda:eu-west-2:211125653762:function:the-alchemiser"
  image_tag: "latest"

# Alert settings
alerts:
  alert_config_s3: "s3://the-alchemiser-s3/alert_config.json"
  cooldown_minutes: 30

# Secrets Manager
secrets_manager:
  region_name: "eu-west-2"
  secret_name: "nuclear-secrets"

# Strategy defaults
strategy:
  default_strategy_allocations:
    nuclear: 0.3
    tecl: 0.5
    klm: 0.2
  poll_timeout: 30
  poll_interval: 2.0

# Email notification configuration
email:
  smtp_server: "smtp.mail.me.com"
  smtp_port: 587
  from_email: "josh@rwxt.org"
  to_email: "josh@rwxt.org" # Optional, defaults to from_email

# Data configuration (preserved from previous config)
data:
  cache_duration: 300
  default_symbol: "AAPL"

# Better Orders execution configuration
better_orders:
  enabled: true
  execution_mode: "auto" # Options: "better_orders", "standard", "auto"

  # Risk management settings
  max_slippage_bps: 20.0
  aggressive_timeout_seconds: 2.5
  max_repegs: 2

  # Market timing settings
  enable_premarket_assessment: true
  market_open_fast_execution: true

  # Spread thresholds (in cents)
  tight_spread_threshold: 3.0
  wide_spread_threshold: 5.0

  # Symbol classification for better orders execution
  leveraged_etf_symbols:
    - "TQQQ"
    - "SQQQ"
    - "TECL"
    - "SPXL"
    - "UPRO"
    - "UVXY"
    - "LABU"
    - "LABD"
    - "SOXL"
    - "FNGU"
    - "FTLS"
    - "FAS"
    - "TNA"
    - "TZA"
    - "CURE"
    - "DIRV"

  high_volume_etfs:
    - "SPY"
    - "QQQ"
    - "TLT"
    - "XLF"
    - "XLK"
    - "XLP"
    - "XLY"
    - "VOX"
    - "VTV"
    - "VOOG"
    - "VOOV"
    - "AGG"
    - "BIL"
    - "BSV"
    - "IWM"
    - "EFA"
    - "VWO"

# Strategy tracking configuration
tracking:
  s3_bucket: "the-alchemiser-s3"
  strategy_orders_path: "strategy_orders/"
  strategy_positions_path: "strategy_positions/"
  strategy_pnl_history_path: "strategy_pnl_history/"
  order_history_limit: 1000 # Maximum orders to keep in recent_orders.json
  # Note: Paper and live trading data are automatically separated with "paper/" and "live/" prefixes
