name: tests
on: [push, pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      DRY_RUN: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -U pip
      - run: pip install -e .[dev,test]
      - run: |
          pytest -q --cov=the_alchemiser --cov-branch \
            --cov-report=term-missing --cov-report=xml --cov-report=html \
            --cov-fail-under=85
      - uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov
